name: Deploy Demo Rust Azure Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Rust function
        run: |
          cd ./src
          cargo build --release

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: DemoRustFunctionApp
          package: ./target/release
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}